'''
<Challenge #2: Choose Your Path!>
<Game Title: The Search of the Ender Scroll>
Author: Lee Zhe Tse (Aaron)
Date: 14/9/2020 - 27/9/2020
Description: This is your second challenge of this course, where we used functions that we learned so fat throughout this course to create a playable game,
             simillar to Dungeons and Dragons. Variables, time module, random module, the "def" module, if/else statements, and loops were used
             when creating this game/project. The game that I've created is an advanture game, which players have to made choices and depends on the 20-sided 
             dice results, it determines wheather they would suceed on their choice that they made. 
'''







import random     #Imports the random module.
import time             #Imports the time module.
totalRoll = 0
intLevel = 0
strLevel = 0                #Set the variable to "0" for their skill level, so that they could be generated by the dice roller later in the game.
spdLevel = 0
gameRetry = "y"             #The main variable for the loop of the game, so that the game would be able to replay.
moderateDiff = 8                
easyDiff = 5                                            #Set variables for 3 difficulity for the first obsticles in the game, which could be changed later.
hardDiff = 13
oneCheckpoint = "y"
oneMiniCheck = "y"
twoCheckpoint = "y"                                         #Set the 6 variables for the loop of the obsticles, enable the users to replay the obsticles when fail.
threeCheckpoint = "y"
finalChoice = "y"
gameOver = "y"
def diceRoller(numDice, numSides):   ##Creates a function for a dice roller for multiple uses.
    global totalRoll              #brings the local "totalRoll" variable
    totalRoll = 0                   #Set it to zero (Remove existing results) because it would be used for multiple times.
    for dirInt in range(numDice):               #Using "for" loops, and will loop based on how many dice that it needs to roll/generate.
        diceRoll = random.randint(1, numSides)              #using the random function to generate a random number from 1 to the number of sides inputed.       
        totalRoll += diceRoll                                   #It will add to the total result so that it would get the total dice results when rolled multiple times.
    return totalRoll                                #Returns the value.

def diceRoller20sides():
    global diceRollerResults
    numberAns = random.randint(1, 20)  #Not using this function in the program. (This was created before)
    diceRollerResults = numberAns
    return diceRollerResults

def lineBreak():        #Creates a line break for sections for the game.
    space()
    print("=========================================================")
    space()

def space():            #Creates a function for a space in the game so instead of typing "print("")" for a space, i could just type "space()"
    print("")
    
#===================Program starts here=====================

while gameRetry == "y":   #Using a while loop for the main loop of the game.
    userName = input("Hi user. Please enter your name to proceed: ")            #Asks the user to enter their username.
    space()
    print("Hello, ", userName, ". Glad to meet you!")   #Greets the user.

    time.sleep(2)               #Delays the next line by the integer inside the brackets per second. (Would be frequently used throughout the game.)

    diceRoller(4, 6)                    #Summons the dice roller for 4 dices with 6 sides
    intLevel = totalRoll//5                 #divides the total results by 5 (rounded up) and add it into the intelligence level.
    print("Your intelligence level: ", intLevel)        #Displays the intelligence level generated by the dice roller.


    diceRoller(4, 6)
    strLevel = totalRoll//5                                     #Same as above but for strength level.
    print("Your strength level: ", strLevel)


    diceRoller(4, 6)
    spdLevel = totalRoll//5                                     #same as above but for speed level.
    print("Your speed level: ", spdLevel)

    time.sleep(2)
    space()
    print("How the game works:")        #Below are the instructions for the game.
    space()
    space()
    print("you will encounter some decision making questions throughout the game.")
    space()
    print("Some questions contain a difficulity level.")
    space()
    print("When choosing the answer with a difficulity level, a 20-sided dice will determine if the decision you'll made will suceed or not.")
    space()
    print("If the amount of the dice rolled is higher than the difficulity level, the choice you made will progress sucessfully,")
    space()
    print("But if the amount is lower than the difficulity level, the choice you made would most likely fail.")
    space()
    print("Some choice you made in the game might unlock additional situations, actions, and different endings.")
    space()
    print("HAVE FUN!")
    space()
    print("P/S: The Intelligence, Strength, and Speed level will determine the endings for the game.")
    print("(Game will start in 30 seconds.)")

    time.sleep(30)  #A huge delay time so that the user would have time reading the instructions.
    space()
    print("(GAME STARTS)")
    lineBreak()

    

    time.sleep(2)
    print("<The Search of The Ender Scroll>")  #Title of the game.
    lineBreak()


    #First part of the story starts here. Below are the storyline.
    time.sleep(3)
    print("In a galazy far, far, away,")
    space()
    print("You were stranded alone in the sand, at a journey of you finding the ender scroll.")
    space()
    print("Along the way, you find a tomb placed in front of you.")

    time.sleep(4)
    space()
    print("It carves the word: 'Legends never die. Only the true legend that believes in themselves would avenge the day.'")
    time.sleep(2)
    space()
    print("'Feel the power of strength inside you,'")
    time.sleep(2)
    print("'Feel the power of intelligence inside you,'")
    time.sleep(2)
    print("'Feel the speed of force inside you.'")
    time.sleep(2)
    print("'If you don't, you've come to the wrong place.'")

    time.sleep(3)
    space()
    print("Suddenly, right after you finish reading, the ground starts rumbling")
    print("You felt like both an earthquake is happening and the world is sinking.")

    time.sleep(3)
    space()
    print("But your guts is wrong. Maybe because of uncertainty.")

    time.sleep(2)
    space()
    print("Instead, a giant mummy has spawn infront of you.")

    time.sleep(2)
    space()
    print("Hitchtakke, the Giant Mummy: 'My name is Hitchtakke. You have come to the wrong place.'")

    time.sleep(2)
    space()
    print("Hitchtakke, the Giant Mummy: 'YOU ARE HERE TO DIE!!!!!!!!!!!!'")
    time.sleep(2)
    space()
    
    #Basically there is an obsticle above for the user to overcome so a while loop would be used below for the obsticle (Which the user could replay).

    while oneCheckpoint == "y":  
        
        space()
        print("He charged to attack you. What would you do?")  #Asks the user on what should they do.


        #Below are the selection for the user to choose and would only suceed if the dice results are more than the difficulity variable set eariler.

        time.sleep(4)
        space()
        print("1. Runnnnnnnnnnnnnnnnnnn! Difficulity: ", hardDiff)
        print("2. Pull out your sword and begin to fight with all of your strength. Difficulity: ", easyDiff)
        print("3. Find your way to locate Hitchtakke's heart and end it. Difficulity: ", moderateDiff)
        firstAns = input("Enter your answer here. (1, 2, 3): ")    #LEts the user to type in the answer they wanted to choose.

        if firstAns == "1":   #If the user chose the first answer,
            diceRoller(1, 20)   #A dice roller(contains 1 die with 20 sides) would be called.

            if totalRoll >= hardDiff:    #If the total dice results is higher or equal than the difficulity, a good storyline progresses.
                print("You run as fast as you could to bypass Hitchtakke, the Giant Mummy.")
                time.sleep(2)
                space()
                print("Dice Rolled: ", totalRoll)
                time.sleep(2)
                space()
                print("You are faster than the giant mummy and could not catch up with you.")
                time.sleep(2)
                space()
                print("After running around 8 miles, you turned back and saw the mummy drown in quick sand.")
                time.sleep(2)
                space()
                print("Seems like an easy win.")
                lineBreak()

                print("Your speed level gained 10 steps up.")
                spdLevel += 10         #Adds 10 to their speed level.
                print("Your Speed Level: ", spdLevel)
                oneCheckpoint = "n"   #Ends the loop.

                time.sleep(5)
                lineBreak()

            elif totalRoll < hardDiff:   #But if the results are lower than the difficulity,
                print("You run as fast as you could to bypass Hitchtakke, the Giant Mummy.")  #Bad storyline progresses.
                time.sleep(2)
                space()
                print("Dice Rolled: ", totalRoll)
                time.sleep(2)
                space()
                print("But as you run, Hitchtakke grabbed your leg and run while dragging you.")
                time.sleep(2)
                space()
                print("You seemed like you regret on what you had done, but you can't do anything at this point.")
                time.sleep(2)
                space()
                print("He smashed you over and over again on a pile of bricks and tears you apart.")
                time.sleep(2)
                space()
                print("You realise that you had been defeated.")
                time.sleep(2)
                space()
                print("Game Over")
                firstGameRetry = "y"   #Creates the loop for the retry section, in case they typed something invalid, which they could type the correct one instead of crashing the program
                lineBreak()

                time.sleep(3)
                while firstGameRetry == "y":
                    print("Retry this round? Or Skip?")
                    print("1. Yes")                                                 #Asking the user if they want to continue the game or retry the obsticle.
                    print("2. Skip")
                    oneCheckpointAns = input("Enter your answers here(1, 2): ")   #Lets them input here.

                    if oneCheckpointAns == "1":         #If they chooses to replay,
                        print("Round will restart, but difficulity will be higher.")  #The difficulity will increase by 1.
                        easyDiff += 1
                        moderateDiff += 1    #As shown here.
                        hardDiff += 1
                        oneCheckpoint = "y"             #Loops the choice selection again,
                        firstGameRetry = "n"                #And stops the retry loop.

                        time.sleep(3)
                        if easyDiff >= 20:     #If the difficulity exceeds 20, (which the difficulity would be impossible for the user to suceed as they are based on a 20-sided dice), 
                            print("You have exceed the number of retries. One of the difficulity level will reset to 5") #It would reset the difficulity back to the original variable.
                            oneCheckpoint = "y"   #The choice selection loop would still loop until the user suceed in the obsticles.
                            easyDiff = 5

                        if moderateDiff >= 20:  #Same as above but for another difficulity level.
                            print("You have exceed the number of retries. One of the difficulity level will reset to 8")
                            oneCheckpoint = "y"
                            moderateDiff = 8

                        if hardDiff >= 20:      #Same as above but for another difficulity level.
                            print("You have exceed the number of retries. One of the difficulity level will reset to 13")
                            oneCheckpoint = "y"
                            hardDiff = 13

                    elif oneCheckpointAns == "2": #But if they chose to continue,
                        print("The game will continue. Your levels will be added by the default settings.")     #It would show the following.
                        oneCheckpoint = "n"             #Both loops will stop and move on,
                        firstGameRetry = "n"
                        intLevel += 10
                        spdLevel += 5               #And variables would be added less than usual.
                        strLevel += 5

                        print("Summary:")
                        print("Your Strength Level: ", strLevel)
                        print("Your Intelligence level: ", intLevel)            #Gives them a summary for their skill levels.
                        print("Your speed level:", spdLevel)


                    else:           #But if the user enters neither skip nor continue, but something invalid,
                        print("Invalid answer, please try again.")  #It will show a warning message,
                        firstGameRetry = "y"            #And lets the user to enter again.

        elif firstAns == "2":  #Same as above but for selection 2.
            diceRoller(1, 20)

            if totalRoll >= easyDiff:
                print("You pull your Eternal sword out. Ready to fight Hitchtakke, the Giant Mummy.")
                time.sleep(2)
                space()
                print("Dice Rolled: ", totalRoll)
                space()
                time.sleep(2)
                print("SLASH!!!!!!!!!!")
                time.sleep(2)
                space()
                print("PUNCH!!!!!!!!!!!!")
                time.sleep(2)
                space()
                print("WOOSH!!!!!!!!!!!!!!!")
                time.sleep(2)
                space()
                print("Hitchtakke could not handle your giant strength that was building inside you.")
                time.sleep(2)
                space()
                print("You let him to bleed, and ask him if there's any last words.")
                time.sleep(2)
                space()
                print("Hitchtakke, the Giant Mummy: 'Hahahahahahahahaha..................'")
                time.sleep(2)
                space()
                print("Hitchtakke, the Giant Mummy: 'You had defeat me........'")
                time.sleep(2)
                print("'Even if you defeat me, you are never gonna take the entire scroll alive!'")
                time.sleep(2)
                space()
                print("Hitchtakke, the Giant Mummy: 'HAHAHAHAHAHAHAHAHAHAHAHAHA!!!!!'")
                time.sleep(2)
                space()
                print("He died right after he laughed.")
                lineBreak()

                time.sleep(4)
                print("Your strength level gained 10 steps up.")
                strLevel += 10
                print("Your strength level: ", strLevel)
                oneCheckpoint = "n"
                

                time.sleep(4)
                lineBreak()


            elif totalRoll < easyDiff:
                print("You pull out your Eternal sword out. Ready to fight Hitchtakke, the Giant Mummy.")

                time.sleep(2)
                space()
                print("Dice Rolled, ", totalRoll)

                time.sleep(2)
                space()
                print("SLASH!!!!!!!")
                time.sleep(2)
                space()
                print("PUNCH!!!!!!!!")
                time.sleep(2)
                space()
                print("WOOSH!!!!!!!!!!!!")
                time.sleep(2)
                space()
                print("After a bunch of series action, Hitchtakke grabbed your neck real hard,")
                time.sleep(2)
                space()
                print("....and press it on the wall.")
                time.sleep(2)
                space()
                print("Hitchtakke, the Giant Mummy: 'You useless little rat........'")
                time.sleep(2)
                space()
                print("He leds you bleed.")
                time.sleep(2)
                space()
                print("You realised that you had been defeated.")

                time.sleep(2)
                print("Game Over")
                firstGameRetry = "y"
                lineBreak()


                time.sleep(3)
                while firstGameRetry == "y":
                    print("Retry this round? Or Skip?")
                    print("1. Yes")
                    print("2. Skip")
                    oneCheckpointAns = input("Enter your answers here(1, 2): ")

                    if oneCheckpointAns == "1":
                        print("Round will restart, but difficulity will be higher.")
                        easyDiff += 1
                        moderateDiff += 1
                        hardDiff += 1
                        oneCheckpoint = "y"
                        firstGameRetry = "n"

                        time.sleep(3)
                        if easyDiff >= 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 5")
                            oneCheckpoint = "y"
                            easyDiff = 5

                        if moderateDiff >= 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 8")
                            oneCheckpoint = "y"
                            moderateDiff = 8

                        if hardDiff >= 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 13")
                            oneCheckpoint = "y"
                            hardDiff = 13

                    elif oneCheckpointAns == "2":
                        print("The game will continue.  Your levels will be added by the default settings.")
                        oneCheckpoint = "n"
                        firstGameRetry = "n"
                        intLevel += 10
                        spdLevel += 5
                        strLevel += 5

                        print("Summary:")
                        print("Your Strength Level: ", strLevel)
                        print("Your Intelligence level: ", intLevel)
                        print("Your speed level:", spdLevel)


                    else:
                        print("Invalid answer, please try again.")
                        firstGameRetry = "y"

        elif firstAns == "3":    #Same as above but for selection 3.
            diceRoller(1, 20)

            if totalRoll >= moderateDiff:
                print("You had choosen to find a way to locate Hitchtakke, the Giant Mummy's heart.")
                time.sleep(2)
                space()
                print("Dice Rolled: ", totalRoll)
                time.sleep(2)
                space()
                print("Based on the Biology course that you had taken in the past,")
                time.sleep(2)
                space()
                print("....you knew exactly where is the human heart located,")
                time.sleep(2)
                space()
                print("But had no clue whether if the Mummy's heart will be located the same,")
                time.sleep(2)
                space()
                print("You pull your eternal sword out, climb your way to Hitchtakke's heart from his legs to his arms,")
                time.sleep(2)
                space()
                print("And slashed his heart from his chest apart without any thoughts.")
                time.sleep(2)
                space()
                print("He bled to death, without leaving any last words.")
                lineBreak()

                time.sleep(4)
                print("Your intelligence level gained 10 steps up.")
                intLevel += 10
                print("Your intelligence level: ", intLevel)
                oneCheckpoint = "n"
                

            elif totalRoll < moderateDiff:
                print("You had choosen to find a way to locate Hitchtakke, the Giant Mummy's heart.")
                time.sleep(2)
                space()
                print("Dice Rolled: ", totalRoll)
                time.sleep(2)
                space()
                print("You had taken Biology courses before, so you should know where the human heart might be located,")
                time.sleep(2)
                space()
                print("But because the condition you're in makes you nervous, you can't remember about it.")
                time.sleep(2)
                space()
                print("You stand still thinking where could his heart might be located,")
                time.sleep(2)
                space()
                print("But you are too late.")
                time.sleep(3)
                space()
                print("Hitchtakke reached to your heart and rip it apart, which makes you bleed a lot.")
                time.sleep(2)
                space()
                print("He left no last words for you.")

                time.sleep(3)
                space()
                print("GAME OVER")
                firstGameRetry = "y"
                lineBreak()


                

                time.sleep(3)
                while firstGameRetry == "y":
                    print("Retry this round? Or Skip?")
                    print("1. Yes")
                    print("2. Skip")
                    oneCheckpointAns = input("Enter your answers here(1, 2): ")

                    if oneCheckpointAns == "1":
                        print("Round will restart, but difficulity will be higher.")
                        easyDiff += 1
                        moderateDiff += 1
                        hardDiff += 1
                        oneCheckpoint = "y"
                        firstGameRetry = "n"

                        time.sleep(3)
                        if easyDiff >= 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 5")
                            oneCheckpoint = "y"
                            easyDiff = 5

                        if moderateDiff >= 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 8")
                            oneCheckpoint = "y"
                            moderateDiff = 8

                        if hardDiff >= 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 13")
                            oneCheckpoint = "y"
                            hardDiff = 13

                    elif oneCheckpointAns == "2":
                        print("The game will continue.  Your levels will be added by the default settings.")
                        oneCheckpoint = "n"
                        firstGameRetry = "n"
                        intLevel += 10
                        spdLevel += 5
                        strLevel += 5

                        print("Summary:")
                        print("Your Strength Level: ", strLevel)
                        print("Your Intelligence level: ", intLevel)
                        print("Your speed level:", spdLevel)


                    else:
                        print("Invalid answer, please try again.")
                        firstGameRetry = "y"
        else:
            print("Invalid answer. Please enter again.")
            oneCheckpoint = "y"

    
    #Basically the game below would follow the same pattern as above, but with some changes.
    #Second part of the story.
    easyDiff = 10
    moderateDiff = 15           #Sets another variable for the difficulities.
    hardDiff = 20
    lineBreak()
    time.sleep(3)
    print("After defeating Hitchtakke, the giant Mummy,")  #Story progresses.
    time.sleep(2)
    space()
    print("You felt like you made some progress into reaching the ender scroll.")
    time.sleep(2)
    space()
    
    if firstAns == "2":   #If the user chose the 2nd selection for their first obsticle, the below storyline would be shown.
        print("But then, you recall on what he had said to you before he died.")
        time.sleep(2)
        space()
        print("'Even if you defeat me, you are never gonna take the entire scroll alive!'")
        time.sleep(2)
        space()
        print("You thought to yourself,")
        time.sleep(2)
        space()
        print("What does that mean?")
        time.sleep(1)
        space()
        print("What does it take to reach that scroll alive without dying?")
        time.sleep(1)
        space()
        print("What's the purpose of the scroll?")
        time.sleep(4)
        space()
        print("As you are feeling furious, you recall on what you had remember back then")
        print("on what your master had said previously.")
        
        
        time.sleep(2)
        space()
        print("Master Yu, the Great One: 'No Matter what, bring that Ender Scroll home.'")
        time.sleep(2)
        space()
        print("Master Yu, the Great One: 'This scroll could save the humanity from extinct.'")
        time.sleep(2)
        space()
        print("Master Yu, the Great one: 'Even if you die during the quest, we are going to honor you for the effort you had done.'")
        
        time.sleep(2)
        space()
        print("After remembering what your master had said, you don't feel furious anymore.")
        time.sleep(2)
        space()
        print("Instead you gained back the confidence as the same as you are fighting Hitchtakke previously.")

    elif firstAns == "1":   #Same as above bur for the 1st selection.
        print("You are feeling mroe confident that you might be able to just run all obsticles on the way like you had did just now.")
        time.sleep(2)
        space()
        print("You thought to yourself:")
        time.sleep(1)
        space()
        print("'Wow! Guess that 4 years of cardio training really makes it worth it!' ")    

    elif firstAns == "3":   #Same as above but for the 3rd selection.
        print("You felt like that you are smart enough to bypass all obsticles in front of you.")
        time.sleep(2)
        space()
        print("You thought to yourself:")
        time.sleep(1)
        space()
        print("'My goodness! Just now was insane! Good thing that I had been studying hard in class for the past few years!'")


    time.sleep(4)
    space()
    print("As you are walking forward, you realised that you had arrived into a street market in the middle of desert.")
    time.sleep(2)
    space()
    print("Inside the market, people were selling a great amount of items and stuff.")
    time.sleep(2)
    space()
    print("From food,")
    time.sleep(1)
    print("groceries,")
    time.sleep(1)
    print("equipments,")
    time.sleep(1)
    print("spells,")
    time.sleep(1)
    print("to potions.")

    time.sleep(2)
    space()
    space()
    print("On the way, you encounter a lady selling potions at the left side of the stall.")
    time.sleep(2)
    space()
    print("The Seller Lady: 'Hi, young man, what's your name?'")
    time.sleep(2)
    space()
    print(userName, ": 'Well, my name is ", userName, ". How are you?'")
    time.sleep(2)
    space()
    print("'The Seller Lady: 'Oh, I'm great. Been enjoying selling for the rest of my life.'")

    time.sleep(2)
    space()
    print("Suddenly, the Seller Lady looks surprised. She then went ahead and take a closer look on you.")

    time.sleep(2)
    space()
    print("The Seller Lady: 'Wow! You seemed..........'")
    time.sleep(2)
    print("'Strong.......'")

    time.sleep(2)
    space()
    print("The Seller Lady: 'I sense this special aura coming out of you......'")
    time.sleep(2)
    space()
    print("The Seller Lady: 'It seems like, some kind of strength that you had.....'")
    time.sleep(2)
    space()
    print("The Seller Lady: 'You realy looks like the Choosen One...........")

    time.sleep(1)
    space()
    print(userName,": 'Wait what? The Choosen what-so?'")

    time.sleep(2)
    space()
    print("You had no idea what was the Seller Lady was talking about.")

    time.sleep(2)
    space()
    print("The Seller Lady: 'Oh sorry nevermind. My apologies.'")
    time.sleep(2)
    space()
    print("The Seller Lady: 'Hey, ", userName, ", since you look so handsome, I'm going to give you one out of three potions I had......")
    time.sleep(2)
    space()
    print("The Seller Lady: 'for free.'")

    time.sleep(3)
    space()

    while oneMiniCheck == "y":   #Same as the choice selection option above. (No dice roller was enabled, so there are no retries. The loop is for invalid answers entered.)
        print("Which one would you choose?")
        space()
        print("1. The Red Potion (Effectiveness: ???????)")
        print("2. The Yellow Potion (Effectiveness: ???????)")
        print("3. The Blue potion (Effectiveness: ?????????)")
        print("4. Decline the offer.")
        oneMiniAns = input("Enter your answer here(1, 2, 3, 4): ")

        if oneMiniAns == "1":
            print("You have choosen to drink the red potion.")
            time.sleep(2)
            space()
            print("After drink the red potion, you felt like you have gotten stronger.")
            time.sleep(3)
            space()
            print("(Your Strength Level has increased by 10)")
            strLevel += 10
            oneMiniCheck = "n"

        elif oneMiniAns == "2":
            print("You have choosen to drink the yellow potion")
            time.sleep(2)
            print("After drinking the yellow potion, you felt like you have gotten the speed to run faster. ")
            time.sleep(3)
            print("(Your speed level has increased by 10)")
            spdLevel += 10
            oneMiniCheck = "n"

        elif oneMiniAns == "3":
            print("You have choosen to drink the blue potion")
            time.sleep(2)
            space()
            print("After drinking the blue potion, you felt like you have gotten smarter.")
            time.sleep(3)
            space()
            print("(Your intelligence level has increased by 10)")
            intLevel += 10
            oneMiniCheck = "n"

        elif oneMiniAns == "4":
            print("You have choosen to decline the offer.")
            time.sleep(2)
            space()
            print("The Seller Lady: 'Why? It might be useful for your nexr quest, ", userName, ".")
            time.sleep(2)
            space()
            print("ME: 'Nevermind, I believe in myself. Thanks for your offer.")
            time.sleep(2)
            space()
            print("The Seller Lady: 'Alright then..........'")
            oneMiniCheck = "n"

        else:
            print("Invalid Answer. Please try again.")
            oneMiniCheck = "y"


    time.sleep(2)
    space()
    print("The Seller Lady: 'Good Luck in your mission!'")
    time.sleep(2)
    space()
    print("You left the market in search for the ender sreoll.")
    time.sleep(2)
    lineBreak()
    time.sleep(1)
    print("Summary:")
    space()
    print("Your Strength Level: ", strLevel)
    print("Your Intelligence level: ", intLevel)
    print("Your speed level:", spdLevel)

    if oneMiniAns == "4":   #If they decline the offer, it would show the warning message.
        space()
        print("(You are in a slight disadvantage since you declined the seller's offer)")
        
    lineBreak()
    time.sleep(3)
    print("While continuing your quest, you started to think about your family.")
    time.sleep(2)
    space()
    print("You reached for your neck chain.")
    time.sleep(2)
    space()
    print("It is a picture of you and your family.")
    time.sleep(2)
    space()
    print("All of you guys are really smiling brightly.")    
    time.sleep(2)
    space()
    print("You thought to yourself,")
    time.sleep(2)
    print("'I'm gonna complete my mission, and return back safely to see my family.'")


    time.sleep(2)
    space()
    space()
    print("Not long after, you reach a temple, which is called <The Golden Temple>, where holds the most, sacred, valueble piece of scroll.")
   
    time.sleep(2)
    space()
    print("The ender scroll.")

    time.sleep(2)
    space()
    print("You walked straight into the temple, attempting to enter the Diamond Gate into the Temple.")

    time.sleep(2)
    space()
    print("Surprisingly, there are only two floors inside the temple, so you think that this might be an easy win.")

    time.sleep(2)
    space()
    print("As you advanced forward, you noticed that there are 40 Guard Statues in the Ground floor.")

    time.sleep(2)
    space()
    print("As you advanced another step, a wind blows straight to the Guards.")

    time.sleep(2)
    space()
    print("The guards started to move!!")

    time.sleep(2)
    space()
    print("They all move in an army position, armed with a spear, ready to charge you.")

    time.sleep(2)
    space()
    print("You have to be quick, or else you'll have no time on defeating them all by once.")

    time.sleep(2)
    space()

    while twoCheckpoint == "y":   #Another choice selection, but the 1st difficulity will not increase if the user retries the game.
        
        print("What should you do?")
        print("1. Charge them all at once using your only Eternal Sword. (Difficulity: ", hardDiff, ")")
        print("2. Find a path which led them into a trap. (Difficulity: ", moderateDiff, ")")
        print("3. Use your intelligence, by climbing your way above the celing, let them to jump above, and have the opportunity to cut them in half one by one.(Difficulity: ", easyDiff, ")")

        secondAns = input("Please enter your answer here. (1,2,3): ")

        if secondAns == "1":
            diceRoller(1,20)

            print("You have choosen to use the eternal sword to charge them all by once.")

            time.sleep(2)
            print("Dice rolled: ", totalRoll)
            space()

            if totalRoll >= hardDiff:
                
                time.sleep(2)
                print("This, might be the dumbest thing you might have done throughout your quest.")

                time.sleep(2)
                space()
                print("It might be a suicide mission.")

                time.sleep(2)
                space()
                print("You close your eyes, pulled out your Eternal Sword, and charge forward.")

                time.sleep(2)
                space()
                print("You remember every skills and tactics that Master Yu has passed down for you, and use them one by one for each and every kill.")

                time.sleep(2)
                space()
                print("After you reached the stairs for the second floor, you opened your eyes.")

                time.sleep(2)
                space()
                print("You turned back, and realised that you had defeated all 40 guards by your own.")

                time.sleep(2)
                space()
                print("You give out a hige sigh, and planned to move forward.")

                time.sleep(2)
                space()
                print("Suddenly, a Guard that is on the ground, granned your leg.")

                if strLevel >= 10:
                    time.sleep(2)
                    space()
                    print("You immediately finished him by giving another two stabs.")

                    time.sleep(2)
                    space()
                    print("You ascend forward.")

                elif strLevel < 10:
                    time.sleep(2)
                    space()
                    print("He grabbed you and pushed you to the ground.")

                    time.sleep(2)
                    space()
                    print("You struggled to get up, and used your strength and give him a stab.")

                    time.sleep(2)
                    space()
                    print("He died, and so you ascend forward.")

                time.sleep(3)
                space()
                print("(Your Strength Level Increases by 10, which is crucial for the final round.)")

                strLevel += 10

                time.sleep(2)
                print("Summary:")
                print("Your Strength Level: ", strLevel)
                print("Your Intelligence level: ", intLevel)
                print("Your speed level:", spdLevel)
                
                
                twoCheckpoint = "n"
                lineBreak()




            
            elif totalRoll < hardDiff:

                time.sleep(2)
                print("This, might be the dumbest thing you might have done throughout your quest.")

                time.sleep(2)
                space()
                print("It might be a suicide mission.")

                time.sleep(2)
                space()
                print("You close your eyes, pulled out your Eternal Sword, and charge forward.")

                time.sleep(2)
                space()
                print("You remember every skills and tactics that Master Yu has passed down for you, and use them one by one for each and every kill.")

                time.sleep(2)
                space()
                print("While you were fighting forward, a Guard grabbed your leg, charge forward to you, and sliced you.")

                time.sleep(2)
                space()
                print("You have been defeated.")

                secondGameRetry = "y"


                time.sleep(3)
                while secondGameRetry == "y":
                    print("Retry this round? Or Skip?")
                    print("1. Yes")
                    print("2. Skip")
                    twoCheckpointAns = input("Enter your answers here(1, 2): ")

                    if twoCheckpointAns == "1":
                        print("Round will restart, but difficulity will be higher.")
                        easyDiff += 1
                        moderateDiff += 1
                        twoCheckpoint = "y"
                        secondGameRetry = "n"

                        time.sleep(3)
                        if easyDiff > 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 10.")
                            twoCheckpoint = "y"
                            easyDiff = 14

                        if moderateDiff > 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 15.")
                            twoCheckpoint = "y"
                            moderateDiff = 16

                    elif twoCheckpointAns == "2":
                        print("The game will continue. Your levels will be added by the default settings.")
                        twoCheckpoint = "n"
                        secondGameRetry = "n"

                        intLevel += 3
                        spdLevel += 5
                        strLevel += 3

                        print("Summary:")
                        print("Your Strength Level: ", strLevel)
                        print("Your Intelligence level: ", intLevel)
                        print("Your speed level:", spdLevel)

                    else:
                        print("Invalid answer, please try again.")
                        secondGameRetry = "y"

        elif secondAns == "2":

            diceRoller(1,20)

            print("You decided to led them into a trap.")

            time.sleep(2)
            print("Dice rolled: ", totalRoll)
            space()

            if totalRoll >= moderateDiff:

                time.sleep(2)
                space()
                print("You run as fast into the left side of the room, and you found a gate.")

                time.sleep(2)
                space()
                print("It turns out that there's a fire pit inside.")

                time.sleep(2)
                space()
                print("You faked going inside the gate, and the guards charged inside.")

                time.sleep(2)
                space()
                print("You have finally baited them inside the gate.")

                if spdLevel >= 10:

                    time.sleep(2)
                    space()
                    print("You quickly closed the gate, and locked them inside.")

                    time.sleep(2)
                    space()
                    print("They realised that they had been tricked, but it was too late.")

                    time.sleep(2)
                    space()
                    print("You ascend forward.")


                elif spdLevel < 10:

                    time.sleep(2)
                    space()
                    print("They realised that they had been tricked, but it was too late.")

                    time.sleep(2)
                    space()
                    print("When you reached to close the gate, another guard gets out of the gate.")

                    time.sleep(2)
                    print("You use your sword to stab him, and after giving him a great stab, you ascend forward.")

                
                time.sleep(3)
                print("(Your Speed Level increased by 10, which was crucial for the next round.")

                spdLevel += 10

                time.sleep(2)
                print("Summary:")
                print("Your Strength Level: ", strLevel)
                print("Your Intelligence level: ", intLevel)
                print("Your speed level:", spdLevel)
                
                
                twoCheckpoint = "n"
                lineBreak()



            elif totalRoll < moderateDiff:

                time.sleep(2)
                space()
                print("You run as fast into the left side of the room, and you found a gate.")

                time.sleep(2)
                space()
                print("It turns out that there's a fire pit inside.")

                time.sleep(2)
                space()
                print("But you are too late.")

                time.sleep(2)
                space()
                print("You are too slow, and the guards grabbed your leg and dragged you into a space. and finished you off.")

                time.sleep(2)
                space()
                print("You have been defeated.")

                secondGameRetry = "y"

                time.sleep(3)
                while secondGameRetry == "y":
                    print("Retry this round? Or Skip?")
                    print("1. Yes")
                    print("2. Skip")
                    twoCheckpointAns = input("Enter your answers here(1, 2): ")

                    if twoCheckpointAns == "1":
                        print("Round will restart, but difficulity will be higher.")
                        easyDiff += 1
                        moderateDiff += 1
                        twoCheckpoint = "y"
                        secondGameRetry = "n"

                        time.sleep(3)
                        if easyDiff > 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 10.")
                            twoCheckpoint = "y"
                            easyDiff = 14

                        if moderateDiff > 20:
                            print("You have exceed the number of retries. One of the difficulity level will reset to 15.")
                            twoCheckpoint = "y"
                            moderateDiff = 16

                    elif twoCheckpointAns == "2":
                        print("The game will continue. Your levels will be added by the default settings.")
                        twoCheckpoint = "n"
                        secondGameRetry = "n"

                        intLevel += 3
                        spdLevel += 5
                        strLevel += 3

                        print("Summary:")
                        print("Your Strength Level: ", strLevel)
                        print("Your Intelligence level: ", intLevel)
                        print("Your speed level:", spdLevel)

                    else:
                        print("Invalid answer, please try again.")
                        secondGameRetry = "y"

        elif secondAns == "3":

            diceRoller(1,20)

            print("You have choosen to do the smart move (～￣▽￣)～.")

            time.sleep(2)
            space()
            print("Dice Rolled: ", totalRoll)

            if totalRoll >= easyDiff: 

                time.sleep(2)
                space()
                print("You managed to find a way to jump up the celing, and stayed there.")
                
                time.sleep(2)
                space()
                print("The guards jumped up, one by one,")

                time.sleep(2)
                space()
                print("And you sliced them, one by one.")

                if intLevel >= 10:
                    
                    time.sleep(2)
                    space()
                    print("After defeating the last guard, you ascent forward to the next floor.")

                elif intLevel < 10:

                    time.sleep(2)
                    space()
                    print("After some time, you had slained most of them.")

                    time.sleep(2)
                    space()
                    print("But then, the last guard grabbed your leg down, and you fell.")

                    time.sleep(2)
                    space()
                    print("You proceed to slice him over and over until he is down.")

                    time.sleep(2)
                    space()
                    print("You ascend forward to the next floor.")

                time.sleep(3)
                space()
                print("(Your intelligence level increased by 10, which is crucial for the final mission.)")

                intLevel += 10

                time.sleep(2)
                print("Summary:")
                print("Your Strength Level: ", strLevel)
                print("Your Intelligence level: ", intLevel)
                print("Your speed level:", spdLevel)
                    
                twoCheckpoint = "n"
                lineBreak() 

            elif totalRoll < easyDiff:
                
                time.sleep(2)
                space()
                print("You managed to find a way to jump up the celing,")

                time.sleep(2)
                space()
                print("But you fell, as you jumped from the wrong side.")

                time.sleep(2)
                space()
                print("After you fell, the guards then finished you off.")

                secondGameRetry = "y"

                time.sleep(3)
                while secondGameRetry == "y":
                    print("Retry this round? Or Skip?")
                    print("1. Yes")
                    print("2. Skip")
                    twoCheckpointAns = input("Enter your answers here(1, 2): ")

                    if twoCheckpointAns == "1":
                        print("Round will restart, but difficulity will be higher.")
                        easyDiff += 1
                        moderateDiff += 1
                        twoCheckpoint = "y"
                        secondGameRetry = "n"

                        time.sleep(3)
                        if easyDiff > 20:
                            print("You have exceed the number of retries. The difficulity will reset to 10.")
                            twoCheckpoint = "y"
                            easyDiff = 14

                        if moderateDiff > 20:
                            print("You have exceed the number of retries. The difficulity will reset to 15.")
                            twoCheckpoint = "y"
                            moderateDiff = 16

                    elif twoCheckpointAns == "2":
                        print("The game will continue.  Your levels will be added by the default settings.")
                        twoCheckpoint = "n"
                        secondGameRetry = "n"

                        intLevel += 3
                        spdLevel += 5
                        strLevel += 3

                        print("Summary:")
                        print("Your Strength Level: ", strLevel)
                        print("Your Intelligence level: ", intLevel)
                        print("Your speed level:", spdLevel)

                    else:
                        print("Invalid answer, please try again.")
                        secondGameRetry = "y"

            else:
                print("Invalid answer. Please try again.")
                twoCheckpoint = "y"


    #Third and last part of the story.
    
    time.sleep(2)
    space()
    print("You went up the stairs.")

    time.sleep(2)
    space()
    print("When you reached the final floor, you saw something glowing at the end of the room.")

    time.sleep(2)
    space()
    print("You take a closer look,")

    time.sleep(2)
    print("And it turns out that it holds something sacred.")

    time.sleep(2)
    space()
    print("The Ender Scroll.")

    time.sleep(2)
    space()
    print("You have finally found the Ender Scroll, after spending 20 years of searching for it.")

    time.sleep(2)
    space()
    print("You could not wait to take hold on the Ender Scroll, but you want to be a little bit careful,")

    time.sleep(2)
    space()
    print("as you sense that there might be some small traps that are set up in he temple.")

    time.sleep(2)
    space()
    print("You attempt to tiptoe yourself to the scroll, avioding some suspicious looking tiles on the floor.")

    time.sleep(2)
    space()
    print("As you tiptoed, you accidentally step on one of the suspicious looking tile.")

    time.sleep(2)
    space()
    print("As you step on it, cracks started to appear on the ground!")

    time.sleep(2)
    space()
    print("It felt like the floor was about to break down.")

    time.sleep(2)
    space()
    print("You run as quickly as you could to reach the Ender Scroll!")

    time.sleep(2)
    space()
    print("Suddenly, the floor started to break, and float upwards!")

    time.sleep(2)
    space()
    print("The entire floor flew up around 10 kilometers, and remained floating in the sky!")

    time.sleep(2)
    space()
    print("After you gained back your balance, you rushed ahead again to the ender scroll")

    time.sleep(2)
    space()
    print("As you looked up, something spawned.....")

    time.sleep(2)
    space()
    print("Seems like...............................")

    time.sleep(2)
    space()
    print("Somebody that has a shape of Bearus from DragonBall....")

    time.sleep(2)
    space()
    print("but its not.")

    time.sleep(2)
    space()
    print("It's a wolf..........")

    time.sleep(3)
    space()
    print("NO!!")

    time.sleep(2)
    space()
    print("A possessed wolf, that seems like the scrollkeeper of the Ender Scroll!")

    time.sleep(2)
    space()
    print(userName, ": 'Who, are you?'")

    time.sleep(2)
    space()
    print("Kubeckkan, The Wolf Boss: 'Why O' Why, you bother ask that nonsense question......'")

    time.sleep(2.5)
    space()
    print("Kubeckkan, The Wolf Boss: 'That everybody asks when they reached here......")

    time.sleep(2)
    space()
    print("Kubeckkan, The Wolf Boss: 'Why not, run away before I finish you?'")

    time.sleep(2)
    space()
    print("You rushed to Kubeckkan, The Wolf Boss.")

    time.sleep(2)
    space()
    print("You throw some punches to him, but you missed,")

    time.sleep(2)
    space()
    print("As he was too fast, not a normal human being could even handle that speed.")
    
    time.sleep(2)
    space()
    print("Kubeckkan then found the opportunity to grab your arm and slammed you on the ground, multiple times.")

    time.sleep(2)
    space()
    print("He even knows magic.")

    time.sleep(2)
    space()
    print("As you throw some Shuriken to him, he teleported.")

    time.sleep(2)
    space()
    print("And teleported to the back of you, and give a great kick to you.")

    time.sleep(2)
    space()
    print("As you fell, wounded, Kubeckkan then teleported in front of you..")

    time.sleep(2)
    space()
    print("Kubeckkan, The Wolf Boss: 'Look, you little weakling......'")

    time.sleep(2)
    space()
    print("Kubeckkan, The Wolf Boss: 'You are too easy for me.....'")

    time.sleep(2)
    space()
    print("Kubeckkan, The Wolf Boss: 'I could even eat you raw..... could even fit into my mouth....'")

    time.sleep(2)
    space()
    print("You need to do something.......FAST!!!!!!!!!!!!")

    time.sleep(3)
    space()

    easyDiff = 13
    moderateDiff = 15   #Variable changed for the next and last obsticles.
    hardDiff = 20

    while threeCheckpoint == "y":   #Simillar to the choice selection above, but if the user fails, the mission would automatically retry and the difficulity will not be increased.
        print("What should you do?")
        space()
        print("1. Find and locate Kubeckkan's weak spot to attack. (Difficulity: ", easyDiff, ")")
        print("2.  Run to the edge, along with another edge so that he won't catch you! (Difficulity: ", moderateDiff, ")" )
        print("3. Do the Shriikurii Combo! (A bright force unleashed with Eternal Sword and Shuriken) (Difficulity:, ", hardDiff, ")")

        thirdAns = input("Enter your answer here. (1,2,3): ")

        if thirdAns == "1":

            diceRoller(1,20)

            print("You chose to locate Kubeckkan's weak spot to attack!")

            time.sleep(2)
            space()
            print("Dice Rolled: ", totalRoll)

            if totalRoll >= easyDiff:

                time.sleep(2)
                space()
                print("Master Yu has taught you on how to locate people's weak spot by using your Sixth Sense. ")

                time.sleep(2)
                space()
                print("You close your eyes, take a deep breath, and sensed the weak spot.")

                time.sleep(2)
                space()
                print("After a while, you sensed his weak spot.")

                time.sleep(2)
                space()
                print(userName, ": 'His Armpits!'")

                time.sleep(2)
                space()
                print("You rushed forward, and punched his armpits in full speed.")

                time.sleep(2)
                space()
                print("Kubeckkan was knocked out.")

                time.sleep(2)
                space()
                print("Kubeckkan then thrown some punches to you,")

                time.sleep(2)
                space()
                print("You pulled out your Eternal Sword, and blocked most of it.")

                time.sleep(2)
                space()
                print("You threw some more punches and more punches until Kubeckkan could not handle the pressure.")


                time.sleep(2)
                space()
                print(userName, ": 'THIS IS IT!!!'")

                time.sleep(2)
                space()
                print("(Your Intelligence gained 15 steps up!)")

                intLevel += 15
                threeCheckpoint = "n"

            
            elif totalRoll < easyDiff:

                time.sleep(2)
                space()
                print("Master Yu has taught you on how to locate people's weak spot by using your Sixth Sense.")

                time.sleep(2)
                space()
                print("You close your eyes, take a deep breath, and sensed the weak spot.")

                time.sleep(2)
                space()
                print("But it turns out that you could not sense it as you lose focus.")

                time.sleep(2)
                space()
                print("But you still have time!")

                threeCheckpoint = "y"

        elif thirdAns == "2":
            

            diceRoller(1, 20)

            print("You chose to run to the edge of the floor. over and over again!")

            time.sleep(2)
            space()
            print("Dice Rolled: ", totalRoll)

            if totalRoll >= moderateDiff:
                

                time.sleep(2)
                space()
                print("You are too fast, until Kubeckkan could not catch up to you,")

                time.sleep(2)
                space()
                print("Even if he teleports, he still could not catch up with you!")

                time.sleep(2)
                space()
                print("You kept running and running until he gets tired.")

                time.sleep(2)
                space()
                print(userName, ": 'THIS IS IT!!!!!!'")

                time.sleep(2)
                space()
                print("(Your speed gained up 15 steps.)")

                spdLevel += 15
                threeCheckpoint = "n"

            elif totalRoll < moderateDiff:

                time.sleep(2)
                space()
                print("You are too fast, but then,")

                time.sleep(2)
                space()
                print("Once Kubeckkan teleports, he kicked you back to the spot that you were in previously!")

                time.sleep(2)
                space()
                print("He moves closer to you.")

                time.sleep(2)
                space()
                print("But you still have time!")

                threeCheckpoint = "y"

        elif thirdAns == "3":

            diceRoller(1,20)

            print("You chose to use Shriikurii Combo (A bright force unleashed with Eternal Sword and Shuriken), using your Eternal Sword!")

            time.sleep(2)
            space()
            print("Dice Rolled: ", totalRoll)

            if totalRoll >= hardDiff:

                time.sleep(2)
                space()
                print("You had never done the Shuriikurii Combo before, ")

                time.sleep(2)
                space()
                print("But you have seen Master Yu done the Shuriikurii Combo before!")

                time.sleep(2)
                space()
                print("You took a deep breath,")

                time.sleep(2)
                space()
                print("And did the combo that Master Yu has taught you.")

                time.sleep(2)
                space()
                print("After doing and commanding some sword movements, you unleashed a bright force, straight towards Kubeckkan.")

                time.sleep(2)
                space()
                print("The force was big, strong, and powerful.")

                time.sleep(2)
                space()
                print("Too strong, Even for Kubeckkan to handle!")

                time.sleep(2)
                space()
                print("He fell down, and you ran as fast as you could to reach the Ender Scroll.")

                time.sleep(2)
                space()
                print(userName,": 'This is it!!!!!!!!'")

                time.sleep(2)
                space()
                print("(Your Strength Level gained 15 steps up.)")

                strLevel += 15

                threeCheckpoint = "n"

            elif totalRoll < hardDiff:

                time.sleep(2)
                space()
                print("You had never done the Shuriikurii Combo before, ")

                time.sleep(2)
                space()
                print("But you have seen Master Yu done the Shuriikurii Combo before!")

                time.sleep(2)
                space()
                print("You took a deep breath,")

                time.sleep(2)
                space()
                print("And did the combo that Master Yu has taught you.")

                time.sleep(2)
                space()
                print("After doing and commanding some sword movements, nothing happened.")

                time.sleep(2)
                space()
                print("OH NO! You made a mistake in one of the movements!")

                time.sleep(2)
                space()
                print("But you still have time!")

                threeCheckpoint = "y"

        else:
            print("Invaild answer. Please try again.")
            threeCheckpoint = "y"

    lineBreak()
    #The last part of the story progresses,
    time.sleep(2)
    print("You run ahead to the Ender Scroll, and touched the Ender Scroll!")

    time.sleep(2)
    space()
    print("The Ender Scroll charges power over you, and you gained a big tramendous power through your veins!")

    time.sleep(2)
    space()
    print("You are glowing, and become very powerful!")

    time.sleep(2)
    space()
    print("Kubeckkan, The Wolf Boss: 'No.....no....NOOOOOOOOO!!!!!!!'")

    time.sleep(2)
    space()
    print(userName, ": 'I am", userName, ", the Choosen One.")

    time.sleep(2)
    space()
    print("Kubeckkan, The Wolf Boss: 'ARRRRRRGHHHHHHHHHHHHHHH!!!!!!!!'")

    time.sleep(2)
    space()
    print("Kubeckkan, the Wolf Boss charged towards you.")

    time.sleep(2)
    space()

    while finalChoice == "y":   #This choice selection lets the user to choose the ending of the game. The user would be able to select the ending if their specific skill level are more than 15.
        print("FINISH HIM!!!!!!")
        space()
        print("i. Use your Intelligence (Intelligence Level Required: 15) (Type'i' to select)")
        print("s. Use Speed (Speed Level Required: 15) (Type 's' to select)")
        print("h. Use your Strength (Speed Level Required: 15) (Type 'h' to select)")

        space()
        space()
        print("Your Levels:")
        space()

        print("Intelligence: ", intLevel)
        print("Strength: ", strLevel)
        print("Speed: ", spdLevel)
        space()
        finalAns = input("Type your answer here!: ")
        space()
        if finalAns == "i" and intLevel >= 15:    #If the user chose one of the ending and met the requirements,
            finalChoice = "n"                       #Story will proceed.
            #The intelligence ending (Normal Ending, but not the best)
            print("You gained this big amount of knowledge that you had gained.")

            time.sleep(2)
            space()
            print("Your mind was glowing, as like you could not handle the power of the scroll.")

            time.sleep(2)
            space()
            print("You use mind control to spread Kubeckkan into pieces, ")

            time.sleep(2)
            print("and threw him far, far, away.")

            time.sleep(2)
            space()
            print("Somehow, you gained back the conscious and then able to control the power the Ender Scroll produced.")

            time.sleep(2)
            space()
            print("After placing dowm the floor to its orignial position,")

            time.sleep(2)
            space()
            print("you opened the Ender Scroll, and read what's inside.")

            time.sleep(2)
            space()
            print("It said:")
            time.sleep(2)
            print("'This scroll gives happiness, and protects the galaxy from being extinct.'")
            time.sleep(2)
            print("'Only the Choosen-One could read the scroll in full.'")
            time.sleep(2)
            print("'Unleash the scroll using the Scroll Generator Tower, which shoots out a beam to protect the galaxy.'")
            time.sleep(2)
            print("'Consume that energy, after using your Intelligence, protect the galaxy by your own, for life.'")
            time.sleep(2)
            print("'If Intelligence skill was not unleashed, the power from the Scroll would be sucked back.'")
            time.sleep(2)
            print("'Stay strong my dude,'")
            time.sleep(2)
            print("'Be brave my warrior'")
            print("'x'")


            time.sleep(4)
            space()
            print("You flew out the sky using Mind Control, and look at the galaxy that you are going to protect for the rest of your life.")

            time.sleep(2)
            space()
            print(userName, ": 'Wow, look that this galaxy that I'm gonna protect for the rest of my life. Kinda cool.'")

            time.sleep(2)
            space()
            print(userName,": 'After I'm done, I'm gonna go back and see my family, am i right?'")

            time.sleep(2)
            space()
            print(userName,": 'Wow it's going to be a long journey. I'm so hyped.'")

            time.sleep(2)
            space()
            print("You flew up even higher, and shoot a large beam at the sky,")

            time.sleep(2)
            space()
            print("that notifies Master Yu, your family, and the people in the galaxy that you'll have find the Ender Scroll,")

            time.sleep(2)
            space()
            print("And ready to start a long journey.")

            time.sleep(2)
            lineBreak()




        elif finalAns == "i" and intLevel < 15: #If they did not met the requirements for the selection they chose, it would tell the user to enter again.
            print("Sorry, this option is locked based on your level.")
            finalChoice = "y"

        elif finalAns == "h" and strLevel >= 15:  #Same as above but for strength ending (Best Ending).
            finalChoice = "n"

            print("YOu pulled out your Eternal Sword, no")

            time.sleep(2)
            space()
            print("It's now called the Great Blossom Sword!")

            time.sleep(2)
            space()
            print("You launched this great force using your Sword, and gives out 684 slices to Kubeckkan.")

            time.sleep(2)
            space()
            print("Kubeckkan is dead, bleeding, being sliced to pieces.")


            time.sleep(2)
            space()
            print("The floor stops floating and returns to it's original place.")

            time.sleep(2)
            space()
            print("And your powers were sucked back into the Scroll.")

            time.sleep(2)
            space()
            print(userName, ": 'My goodness. It's finally over! It's finally over!'")

            time.sleep(2)
            space()
            print("You opened the Ender Scroll, and read what's inside.")


            time.sleep(2)
            space()
            print("It said:")
            time.sleep(2)
            print("'This scroll gives happiness, and protects the galaxy from being extinct.'")
            time.sleep(2)
            print("'Only the Choosen-One could read the scroll in full.'")
            time.sleep(2)
            print("'Unleash the scroll using the Scroll Generator Tower, which shoots out a beam to protect the galaxy.'")
            time.sleep(2)
            print("'Consume that energy, after using your Intelligence, protect the galaxy by your own, for life.'")
            time.sleep(2)
            print("'If Intelligence skill was not unleashed, the power from the Scroll would be sucked back.'")
            time.sleep(2)
            print("'Stay strong my dude,'")
            time.sleep(2)
            print("'Be brave my warrior'")
            print("'x'")


            time.sleep(2)
            space()
            print("The next day, after 22 hours of travelling, you returned back to Master Yu's Den, and showed him the Ender Scroll.")

            time.sleep(2)
            space()
            print("                                                         ")
            print("                                                         ")
            print("      /*****************************************\        ")
            print("    /**-------&&-----------&&&&&---------------**\       ")
            print("   /***---&&&-----------------------&&&--------***\      ")
            print(" /****---------&&------------------------&&------***\    ")
            print("/*****----&&------------------------&&&----------*****\  ")
            print("  [|+++++++++++++++++++++++++++++++++++++++++++++++|     ")
            print("   |                                               |     ")
            print("   |                                               |     ")
            print("   |     /////////                /////////        |     ")
            print("   |     /////////                /////////        |     ")
            print("   |     |*******|                |*******|        |     ")
            print("   |     |&&&&&&&|                |&&&&&&&|        |     ")
            print("   |      -------      ●◡●         -------         |     ")
            print("   |               )____YU____(                    |     ")
            print("   |              _____________                    |     ")
            print("   |         (&) {      |      }  (&)              |     ")
            print("   |         (&) |      |      |  (&)              |     ")
            print("   |         (&) |   (●)|(●)   |  (&)              |     ")
            print("   |         (&) |      |      |  (&)              |     ")
            print("   |         (&) |      |      |  (&)              |     ")
            print("   [_______________________________________________]     ")

            time.sleep(2)
            space()
            print("Master Yu, the Great One: 'Oh my great goodness, my Choosen-One is back!'")

            time.sleep(2)
            space()
            print("Master Yu, the Great One: 'My goodness, never thought you might returned! It's been a long time!'")

            time.sleep(2)
            space()
            print("Master Yu, the Great One: 'I'm so worried about you!'")

            time.sleep(2)
            space()
            print(userName,": 'I knew I would be back!'")

            time.sleep(2)
            space()
            print("Both of you guys give each other's hug, and went into a chamber, where the Scroll Generator Tower is placed.")

            time.sleep(2)
            space()
            print("Master Yu, the Great One: 'You ready to see this magic?'")

            time.sleep(2)
            space()
            print(userName, ": 'Well, who's not ready for this to happen?'")

            time.sleep(2)
            space()
            print("Master Yu, the Great One, placed the Scroll into the Tower.")

            time.sleep(2)
            space()
            print("After a few seconds, the Tower shoots out a bright beam to the sky.")

            time.sleep(2)
            space()
            print(userName, ": 'Wow!'")

            time.sleep(2)
            space()
            print("Master Yu, the Great One: 'I know, right?'")

            time.sleep(2)
            space()
            print("This notifies that the scroll has been found, and no more bad, weird monsters will attack our galaxy anymore.")

            time.sleep(4)
            space()
            print("Later that night, you went back to your house, after a long time.")

            time.sleep(2)
            space()
            print("You were so happy to see your family and your spouse.")

            time.sleep(2)
            space()
            print("You were surprised to see your children, who had grown over the years.")

            time.sleep(2)
            space()
            print(userName, ": 'Wow! Look at you guys! You're almost taller than me!'")

            time.sleep(2)
            space()
            print("You guys had a great night, and stayed happily with your family.")

            time.sleep(2)
            space()
            print("The Galaxy remained peaceful throughout the years.")

            time.sleep(2)
            lineBreak()




        elif  finalAns == "h" and strLevel < 15:
            print("Sorry, this option is locked based on your level.")
            finalChoice = "y"

        elif finalAns == "s" and spdLevel >= 15:  #Same as above but for speed ending (Worst Ending.)
            finalChoice = "n"

            print("You unleashed this speed that you could not handle.")


            time.sleep(2)
            space()
            print("Your shoes turned into blades, and begins to rush to Kubeckkan in full speed.")

            time.sleep(2)
            space()
            print("You sliced Kubeckkan in quarters, defeating him.")

            time.sleep(2)
            space()
            print("But you are too fast, which makes you to advanced up in the sky, and you could not stop.")

            time.sleep(2)
            space()
            print("After 8 hours, you finally stopped, but you are floating in outer space, starting to lose consciousness..")

            time.sleep(2)
            space()
            print("You had completed you mission.")
            time.sleep(2)
            print("But at what cost?")
            time.sleep(2)
            print("You are stuck in outer space forever, along with the Scroll.")
            time.sleep(2)
            print("You could not bring the Scroll back to Master Yu,")
            time.sleep(2)
            print("You could not see your family,")
            time.sleep(2)
            print("And lastly, you fail to protect the Galaxy.")

            time.sleep(2)
            space()
            print("Slowly, slowly, your heartbeat stops, and that's the end of your life.")

            time.sleep(2)
            space()
            print("The next day, more creepy monster began to envade the galaxy after the defeat of Kubeckkan.")

            time.sleep(2)
            space()
            print("So this is how the story is gonna end. Right?")



        elif finalAns == "s" and spdLevel < 15:
            print("Sorry, this option is locked based on your level.")
            finalChoice = "y"

        else:
            print("Invalid Answer. Please type again.")













#========================GAME ENDS========================

    time.sleep(4)
    print("THE END")
    print("Retry?")    #Asks the user if they want to retry the game.
    if intLevel < 15 or spdLevel < 15 or strLevel < 15:   #If one of the user's skill level did not reach 15 and above,
        print("(Retry the game to unlock more endings for the game!)")  #The game would recommend the user to play again and chose a different ending.

    
    print("y. Yes")
    print("n. No")

    while gameOver == "y":    
        gameRetryAns = input("Enter your answer here (y/n): ")   #Lets the user to enter their answer.

        if gameRetryAns == "y":   #If they chose to play again,
            gameRetry = "y"
            oneCheckpoint = "y"
            twoCheckpoint = "y"
            threeCheckpoint = "y"    #All username datas, skill level datas, and loops wil be reseted.
            oneMiniCheck = "y"
            finalChoice = "y"
            gameOver = "n"


        elif gameRetryAns == "n": #If not, the game will stop and the loop will break also.
            print("Thanks for playing!!!!!!")
            gameOver = "n"
            gameRetry = "n"

        else:   #If the user enters something invalid,
            print("Invalid Answer. Please try again.")   #It would ask the user to enter the answer again.
            gameOver = "y"



